app/SplitMe/Areas/Administration/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Domain;
using SplitMe.Common.Data;
using SplitMe.Domain.Api;
using SplitMe.Controllers;
using System.Web.Configuration;
using SplitMe.Apns;

namespace SplitMe.Areas.Administration.Controllers
{
    public class GenreController : SplitMeController
    {
        
        // GET: /Admin/Genre/
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public GenreController()
        {
			//CacheLockMask = "Lock-" + _name + "[{0}-{1}]";
		}

		//[RequireSiteFilter]
		//[NavigationHistoryFilter(IsMileStone=true)]
        [Authorize(Roles = "SysAdmin")]
		public ActionResult List() {

            List<Genre> genres = Genre.FetchAll(CurrentUserId, null);

			return View(genres);
		}

        //[OutputCache(Duration = 1, Location = OutputCacheLocation.None, NoStore = true)]
        //[RequireSiteFilter]
        //[NavigationHistoryFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Edit(Guid code)
        {
            Genre obj = null;
            obj = Genre.Fetch(code, CurrentUserId, null);
            string title = "Edit Genre";

            if (obj == null)
            {
                //return NotFound();
                obj = Genre.New();
                obj.Code = code;
                obj.IsNew = true;
                title = "Add New Genre";
            }
            else
            {
                obj.IsNew = false;
            }
            ViewBag.PageTitle = title;

            //PushManager pm = new PushManager();
            //pm.SendTestPush();
            return View(obj);
        }

        [ActionName("Edit")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnEdit(Guid code, string txtGenre)
        {

            Genre obj = null;
            obj = Genre.Fetch(code, CurrentUserId, null);

            if (obj == null)
            {
                obj = Genre.New();
                obj.IsNew = true;
                obj.Code = code;
                // do allergy not found error
                //ModelState.AddModelError("_FORM", "Failed to retrieve diet.");
                //return ShowValidation(model);
            }
            else
            {
                obj.IsNew = false;
            }

            try
            {
                string logoBasePath = WebConfigurationManager.AppSettings["LogoPath"].ToString();
                string savedPath = SaveFile(Request.Files["logoPath"], logoBasePath);
                obj.GenreText = txtGenre.Trim();
                obj.LogoPath = savedPath;
                obj.Save( CurrentUserId, null);
            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            //return View();
            return Redirect(Url.Action("List"));
        }

        //[RequireSiteFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Add()
        {
            return RedirectToAction("Edit", new { code = Guid.NewGuid()});
            //return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Delete(Guid code)
        {
            Genre obj = null;
            //TODO : FIX HACK
            try
            {
                obj = Genre.Fetch(code, CurrentUserId, null);

                if (obj != null)
                    obj.Delete(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    deleted = false
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                deleted = true
            }, JsonRequestBehavior.AllowGet);
        }

        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////API METHODS //////////////////////////////////////////////////////////////////////////////
        public JsonResult GetAll()
        {
            try
            {
                List<Genre> gens = Genre.FetchAll(CurrentUserId, null);
                List<ApiGenre> genres = new List<ApiGenre>();
                foreach (Genre gen in gens)
                {
                    genres.Add(new ApiGenre { Code = gen.Code, Genre = gen.GenreText, LogoPath = gen.LogoPath });
                }
                return Json(new { Success = true, Data = genres }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

app/SplitMe/Areas/Data1/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Domain;
using SplitMe.Common.Data;
using SplitMe.Domain.Api;
using SplitMe.Controllers;
using System.Web.Configuration;
using SplitMe.Apns;

namespace SplitMe.Areas.Data.Controllers
{
    public class GeneralController : SplitMeController
    {
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult SendPush()
        {
            return View();
        }

        [ActionName("SendPush")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnSendPush(string txtToken)
        {
            PushManager pm = new PushManager();
            pm.SendTestPush(txtToken, "Test Push Notification!");
            return Redirect(Url.Action("SendPush"));
        }
        /// <summary>
        /// Api Call for login
        /// </summary>
        /// <param name="deviceToken"></param>
        /// <param name="fbId"></param>
        /// <returns></returns>
        public JsonResult Login(string deviceToken, string fbId, string fbName)
        {
            try
            {
                Player player = Player.Login(deviceToken, fbId, fbName, null);
                return Json(new { Success = true, Data = player }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Api Call for login
        /// </summary>
        /// <param name="deviceToken"></param>
        /// <param name="fbId"></param>
        /// <returns></returns>
        public JsonResult Challenge(string toFbID, string fromFbId, Guid code)
        {
            string fromUserFbName = string.Empty;
            try
            {
                string deviceToken = Player.Challenge(toFbID, fromFbId, ref code, ref fromUserFbName, null);
                PushManager pm = new PushManager();
                pm.Challenge(deviceToken, code, fromUserFbName);
                return Json(new { Success = true, Data = "" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Accept the challenge
        /// </summary>
        /// <param name="chKey"></param>
        /// <returns></returns>
        public JsonResult Accept(Guid chKey)
        {
            string fromUserFbName = string.Empty;
            try
            {
                ApiLyrics apiLyrics = Player.Accept(chKey, null);
                return Json(new { Success = true, Data = apiLyrics }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// //////Submit Answer of Lyrics
        /// </summary>
        /// <param name="chKey"></param>
        /// <returns></returns>
        public JsonResult SubmitAnswer(Guid chKey, int timeTaken, bool isCorrect)
        {
            int totalScore = 0;
            try
            {
                totalScore = Player.SubmitAnswer(chKey, timeTaken, isCorrect, null);
                return Json(new { Success = true, Data = totalScore }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

app/SplitMe/Areas/Administration/Views/Genre/Add.cshtml
@model SplitMe.Domain.Genre

@{
    ViewBag.Title = "Add New Genre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

app/SplitMe/Areas/Administration/Views/Genre/Edit.cshtml
@model SplitMe.Domain.Genre

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@section SubNavigation {
    
}*@

@using (Ajax.BeginForm("Edit", new { code = Request["code"] }, new AjaxOptions { LoadingElementId = "updating", UpdateTargetId = "validation" }, new { id = "targetform", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
        <h2>@ViewBag.PageTitle</h2>

        <div class="row">
            <div class="span3">&nbsp;</div>
                <div class="span8">

                <div class="control-group">
                    <label class="control-label" for="txtGenre">
                        Genre Text</label>
                    <div class="controls">
                        @Html.TextBox("txtGenre", Model.GenreText, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="span3">&nbsp;</div>
                <div class="span8">

                <div class="control-group">
                    <label class="control-label" for="txtLogo">
                        Logo</label>
                    <div class="controls">
                        <input type="file" class="textbox" name="logoPath"/>
                    </div>
                </div>
            </div>
        </div>
        
        string delScript = "deleteGenre('"+ Model.Code +"');";
    
        <div class="row">
            <div class="span12 well centered">
			    <a class="btn btn-danger" href="#" onclick="@delScript"><i class="icon-trash icon-white"></i> Delete</a>
			    <a class="btn btn-primary" href="#"  onclick="$('#targetform').submit();">Save</a>
            </div>
        </div>
}

app/SplitMe/Areas/Administration/Views/Genre/List.cshtml
@model List<SplitMe.Domain.Genre>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="span2 well centered">
		<a class="btn btn-primary" href="@Url.Action("Add", "Genre")">Add New</a>
    </div>
</div>

<div class="row">
    <div id="dvRecipes" class="span12">
        <table id="genreList" class="table table-bordered table-condensed"  cellspacing="0">
    <thead>
        <tr>
            <th>
                Action
            </th>
			<th>
                Genre
            </th>
            <th>
                Logo
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            string style = string.Empty;
            int ix = 0;
            string basePath = System.Web.Configuration.WebConfigurationManager.AppSettings["LogoPath"].ToString();
			foreach (SplitMe.Domain.Genre gen in Model)
            {
                style = ix % 2 == 0 ? "AltListItem" : "ListItem";
                //string path = @Url.Content(gen.LogoPath);
                ix++;
             
                <tr class="@style">
                    <td>
                            @Html.ActionLink("Edit", "Edit", "Genre", new { area = "Administration", code = gen.Code }, null)
                    </td>
                    <td>
                        @gen.GenreText
                    </td>
                    <td>
                       @if(!string.IsNullOrEmpty(gen.LogoPath))
                       {
                            string relPath = basePath + gen.LogoPath;
                            <img src="@Url.Content(relPath)" alt="No Image" height="2"/>
                       }
                        else
                        {
                           <p>No Image</p>
                       }
                    </td>
                </tr>
            }
        }
    </tbody>

</table>
    </div>
</div>