app/SplitMe/Areas/Administration/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Domain;
using SplitMe.Common.Data;
using SplitMe.Domain.Api;
using SplitMe.Controllers;

namespace SplitMe.Areas.Administration.Controllers
{
    public class ArtistController : SplitMeController
    {
        // GET: /Admin/Artist/
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public ArtistController()
        {
			//CacheLockMask = "Lock-" + _name + "[{0}-{1}]";
		}

		//[RequireSiteFilter]
		//[NavigationHistoryFilter(IsMileStone=true)]
        [Authorize(Roles = "SysAdmin")]
		public ActionResult List() {

            List<Artist> Artists = Artist.FetchAll(CurrentUserId, null);

			return View(Artists);
		}

        //[OutputCache(Duration = 1, Location = OutputCacheLocation.None, NoStore = true)]
        //[RequireSiteFilter]
        //[NavigationHistoryFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Edit(Guid id)
        {
            Artist obj = null;
            obj = Artist.Fetch(id, CurrentUserId, null);
            string title = "Edit Artist";

            if (obj == null)
            {
                //return NotFound();
                obj = Artist.New();
                obj.Id = id;
                obj.IsNew = true;
                title = "Add New Artist";
            }
            else
            {
                obj.IsNew = false;
            }
            ViewBag.PageTitle = title;
            return View(obj);
        }

        [ActionName("Edit")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnEdit(Guid id, string txtName)
        {

            Artist obj = null;
            obj = Artist.Fetch(id, CurrentUserId, null);

            if (obj == null)
            {
                obj = Artist.New();
                obj.IsNew = true;
                obj.Id = id;
                // do allergy not found error
                //ModelState.AddModelError("_FORM", "Failed to retrieve diet.");
                //return ShowValidation(model);
            }
            else
            {
                obj.IsNew = false;
            }

            try
            {
                obj.Name = txtName.Trim();
                obj.Save( CurrentUserId, null);

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            //return View();
            return Redirect(Url.Action("List"));
        }

        //[RequireSiteFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Add()
        {
            return RedirectToAction("Edit", new { id = Guid.NewGuid()});
            //return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Delete(Guid id)
        {
            Artist obj = null;
            //TODO : FIX HACK
            try
            {
                obj = Artist.Fetch(id, CurrentUserId, null);

                if (obj != null)
                    obj.Delete(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    deleted = false
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                deleted = true
            }, JsonRequestBehavior.AllowGet);
        }

        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////API METHODS //////////////////////////////////////////////////////////////////////////////
        //public JsonResult GetAll()
        //{
        //    try
        //    {
        //        List<Artist> gens = Artist.FetchAll(CurrentUserId, null);
        //        List<ApiArtist> Artists = new List<ApiArtist>();
        //        foreach (Artist gen in gens)
        //        {
        //            Artists.Add(new ApiArtist { Code = gen.Code, Artist = gen.ArtistText });
        //        }
        //        return Json(new { Success = true, Data = Artists }, JsonRequestBehavior.AllowGet);

        //    }
        //    catch (Exception ex)
        //    {

        //        return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
        //    }
        //}
    }
}

app/SplitMe/Areas/Data1/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Domain;
using SplitMe.Common.Data;
using SplitMe.Domain.Api;
using SplitMe.Controllers;

namespace SplitMe.Areas.Data.Controllers
{
    public class ArtistController : SplitMeController
    {
        // GET: /Admin/Artist/
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public ArtistController()
        {
            //CacheLockMask = "Lock-" + _name + "[{0}-{1}]";
        }

        //[RequireSiteFilter]
        //[NavigationHistoryFilter(IsMileStone=true)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult List()
        {

            List<Artist> Artists = Artist.FetchAll(CurrentUserId, null);

            return View(Artists);
        }

        //[OutputCache(Duration = 1, Location = OutputCacheLocation.None, NoStore = true)]
        //[RequireSiteFilter]
        //[NavigationHistoryFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Edit(Guid id)
        {
            Artist obj = null;
            obj = Artist.Fetch(id, CurrentUserId, null);
            string title = "Edit Artist";

            if (obj == null)
            {
                //return NotFound();
                obj = Artist.New();
                obj.Id = id;
                obj.IsNew = true;
                title = "Add New Artist";
            }
            else
            {
                obj.IsNew = false;
            }
            ViewBag.PageTitle = title;
            return View(obj);
        }

        [ActionName("Edit")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnEdit(Guid id, string txtName)
        {

            Artist obj = null;
            obj = Artist.Fetch(id, CurrentUserId, null);

            if (obj == null)
            {
                obj = Artist.New();
                obj.IsNew = true;
                obj.Id = id;
                // do allergy not found error
                //ModelState.AddModelError("_FORM", "Failed to retrieve diet.");
                //return ShowValidation(model);
            }
            else
            {
                obj.IsNew = false;
            }

            try
            {
                obj.Name = txtName.Trim();
                obj.Save(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            //return View();
            return Redirect(Url.Action("List"));
        }

        //[RequireSiteFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Add()
        {
            return RedirectToAction("Edit", new { id = Guid.NewGuid() });
            //return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Delete(Guid id)
        {
            Artist obj = null;
            //TODO : FIX HACK
            try
            {
                obj = Artist.Fetch(id, CurrentUserId, null);

                if (obj != null)
                    obj.Delete(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    deleted = false
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                deleted = true
            }, JsonRequestBehavior.AllowGet);
        }

        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////API METHODS //////////////////////////////////////////////////////////////////////////////
        //public JsonResult GetAll()
        //{
        //    try
        //    {
        //        List<Artist> gens = Artist.FetchAll(CurrentUserId, null);
        //        List<ApiArtist> Artists = new List<ApiArtist>();
        //        foreach (Artist gen in gens)
        //        {
        //            Artists.Add(new ApiArtist { Code = gen.Code, Artist = gen.ArtistText });
        //        }
        //        return Json(new { Success = true, Data = Artists }, JsonRequestBehavior.AllowGet);

        //    }
        //    catch (Exception ex)
        //    {

        //        return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
        //    }
        //}
    }
}

app/SplitMe/Areas/Administration/Views/Artist/Edit.cshtml
@model SplitMe.Domain.Artist

@{
    ViewBag.Title = "Edit Artist Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@section SubNavigation {
    
}*@

@using (Ajax.BeginForm("Edit", new {id = Request.Url.Segments[4] }, new AjaxOptions { LoadingElementId = "updating", UpdateTargetId = "validation" }, new { id = "targetform", @class = "form-horizontal" }))
{
        <h2>@ViewBag.PageTitle</h2>

        <div class="row">
            <div class="span3">&nbsp;</div>
                <div class="span8">

                <div class="control-group">
                    <label class="control-label" for="txtName">
                        Artist Name</label>
                    <div class="controls">
                        @Html.TextBox("txtName", Model.Name, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>
                </div>
            </div>
        </div>
      
        string delScript = "deleteArtist('"+ Model.Id +"');";
    
        <div class="row">
            <div class="span12 well centered">
			    <a class="btn btn-danger" href="#" onclick="@delScript"><i class="icon-trash icon-white"></i> Delete</a>
			    <a class="btn btn-primary" href="#"  onclick="$('#targetform').submit();">Save</a>
            </div>
        </div>
}

app/SplitMe/Areas/Administration/Views/Artist/List.cshtml
@model List<SplitMe.Domain.Artist>

@{
    ViewBag.Title = "Artist List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="span2 well centered">
		<a class="btn btn-primary" href="@Url.Action("Add", "Artist")">Add New</a>
    </div>
</div>

<div class="row">
    <div id="dvArtists" class="span12">

    @{if (Model == null || Model.Count <= 0)
    {
        Html.RenderPartial("NoRecords", "");

    }
    else
    {
        <table id="genreList" class="table table-bordered table-condensed"  cellspacing="0">
            <thead>
                <tr>
                    <th>
                        Action
                    </th>
			        <th>
                        Atrist
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                    string style = string.Empty;
                    int ix = 0;
			        foreach (SplitMe.Domain.Artist a in Model)
                    {
                        style = ix % 2 == 0 ? "AltListItem" : "ListItem";

                        ix++;
             
                        <tr class="@style">
                        <td valign="top" width="75px">
                                @Html.ActionLink("Edit", "Edit", "Artist", new { area = "Administration", id = a.Id }, null)
                        </td>
                        <td valign="top" width="285px">
                            @a.Name
                        </td>
                        </tr>
                    }
                }
            </tbody>

        </table>
       }
      }
    </div>
</div>