app/SplitMe/Areas/Administration/Controllers/LyricsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Common;
using SplitMe.Domain;
using SplitMe.MVC.Extensions;
using SplitMe.Common.Data;
using SplitMe.Controllers;
using SplitMe.Domain.Api;

namespace SplitMe.Areas.Administration.Controllers
{
    public class LyricsController : SplitMeController
    {
        // GET: /Admin/Lyrics/
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public LyricsController()
        {
			//CacheLockMask = "Lock-" + _name + "[{0}-{1}]";
		}

		//[RequireSiteFilter]
		//[NavigationHistoryFilter(IsMileStone=true)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult List(int? page, string sidx, string sord, string st, string so, string sc)
        {
            IList<ItemDTO> items = new List<ItemDTO> {
				new ItemDTO { Text = "Genre", Value = "1" },
                new ItemDTO { Text = "Title", Value = "2" },
                new ItemDTO { Text = "Text", Value = "3" },
                new ItemDTO { Text = "Artist", Value = "4" },
			};

            MvcHelper.SetSearchViewData(ViewData, so, st, sc, items);
            SplitMe.Common.Data.IPagedList<Lyrics> lyricss = Lyrics.Search(page ?? 1, 30, so, st, sc, sidx, sord, null);
            //List<Lyrics> genres = (List<Lyrics>)Lyrics.Search(page??1, 30, sidx, sord, st, so, sc, null);
            return View(lyricss);
		}

        //[OutputCache(Duration = 1, Location = OutputCacheLocation.None, NoStore = true)]
        //[RequireSiteFilter]
        //[NavigationHistoryFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Edit(Guid code)
        {
            Lyrics obj = null;
            obj = Lyrics.Fetch(code, null, CurrentUserId);
            string title = "Edit Lyrics";

            if (obj == null)
            {
                //return NotFound();
                obj = Lyrics.New();
                obj.Code = code;
                obj.IsNew = true;
                title = "Add New Lyrics";
                obj.Genre = Genre.New();
                obj.Artist = Artist.New();
                obj.Genre.Code = Guid.NewGuid();
                obj.Artist.Id = Guid.NewGuid();
            }
            else
            {
                obj.IsNew = false;
            }
            List<ItemDTO> genres = new List<ItemDTO>();
            List<Genre> gens = Genre.FetchAll(CurrentUserId, null);
            foreach (Genre genre in gens)
            {
                genres.Add(new ItemDTO { Text = genre.GenreText, Value = genre.Code.ToString() });
            }
            ViewData["Genres"] = new SelectList(genres, "Value", "Text", obj.Genre.GenreText);

            List<ItemDTO> artists = new List<ItemDTO>();
            List<Artist> arts = Artist.FetchAll(CurrentUserId, null);
            foreach (Artist a in arts)
            {
                artists.Add(new ItemDTO { Text = a.Name, Value = a.Id.ToString() });
            }
            ViewData["artists"] = new SelectList(artists, "Value", "Text", obj.Artist.Name);

            ViewBag.PageTitle = title;
            return View(obj);
        }

        [ActionName("Edit")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnEdit(Guid code, string txtTitle, string txtText, Guid Genres, Guid artists, string txtCorrectAnswer, string txtWrongAnswer1, string txtWrongAnswer2, string txtWrongAnswer3 )
        {

            Lyrics obj = null;
            obj = Lyrics.Fetch(code,null, CurrentUserId);

            //obj.IsNew = false;
            if (obj == null)
            {
                obj = Lyrics.New();
                obj.IsNew = true;
                obj.Code = code;
            }
            else
                obj.IsNew = false;

            try
            {
                obj.Title = txtTitle.Trim();
                obj.LyricsText = txtText.Trim();
                obj.CorrectAnswer = txtCorrectAnswer;
                obj.WrongAnswer1 = txtWrongAnswer1;
                obj.WrongAnswer2 = txtWrongAnswer2;
                obj.WrongAnswer3 = txtWrongAnswer3;

                Genre genre = Genre.New();
                genre.Code = Genres;
                obj.Genre = genre;

                Artist a = Artist.New();
                a.Id = artists;
                obj.Artist = a;

                obj.Save( CurrentUserId, null);

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            //return View();
            return Redirect(Url.Action("List"));
        }

        //[RequireSiteFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Add()
        {
            return RedirectToAction("Edit", new { code = Guid.NewGuid()});
            //return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Delete(Guid code)
        {
            Lyrics obj = null;
            //TODO : FIX HACK
            try
            {
                obj = Lyrics.Fetch(code, null, CurrentUserId);

                if (obj != null)
                    obj.Delete(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    deleted = false
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                deleted = true
            }, JsonRequestBehavior.AllowGet);
        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////API METHODS///////////////////////////////////////////////////////////////
        public JsonResult GetByGenre(Guid code)
        {
            try
            {
                List<Lyrics> ques = Lyrics.FetchByGenre(code, null, CurrentUserId);
                List<ApiShortLyrics> lyricss = new List<ApiShortLyrics>();
                foreach (Lyrics q in ques)
                {
                    lyricss.Add(new ApiShortLyrics { 
                        Code = q.Code, Title = q.Title,
                        Text = q.LyricsText, Artist = q.Artist.Name});
                }
                return Json(new { Success = true, Data = lyricss }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Get(Guid code)
        {
            try
            {
                Lyrics ques = Lyrics.Fetch(code, null, CurrentUserId);

                ApiLyrics q = new ApiLyrics
                {
                    Code = ques.Code,
                    Title = ques.Title,
                    Text = ques.LyricsText,
                    CorrectAnswer = ques.CorrectAnswer,
                    WrongAnswer1 = ques.WrongAnswer1,
                    WrongAnswer2 = ques.WrongAnswer2,
                    WrongAnswer3 = ques.WrongAnswer3
                };

                return Json(new { Success = true, Data = q }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

app/SplitMe/Areas/Data1/Controllers/LyricsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SplitMe.Common;
using SplitMe.Domain;
using SplitMe.MVC.Extensions;
using SplitMe.Common.Data;
using SplitMe.Controllers;
using SplitMe.Domain.Api;

namespace SplitMe.Areas.Data.Controllers
{
    public class LyricsController : SplitMeController
    {
        // GET: /Admin/Lyrics/
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Index()
        {
            return View();
        }

        public LyricsController()
        {
            //CacheLockMask = "Lock-" + _name + "[{0}-{1}]";
        }

        //[RequireSiteFilter]
        //[NavigationHistoryFilter(IsMileStone=true)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult List(int? page, string sidx, string sord, string st, string so, string sc)
        {
            IList<ItemDTO> items = new List<ItemDTO> {
				new ItemDTO { Text = "Genre", Value = "1" },
                new ItemDTO { Text = "Title", Value = "2" },
                new ItemDTO { Text = "Text", Value = "3" },
                new ItemDTO { Text = "Artist", Value = "4" },
			};

            MvcHelper.SetSearchViewData(ViewData, so, st, sc, items);
            SplitMe.Common.Data.IPagedList<Lyrics> lyricss = Lyrics.Search(page ?? 1, 30, so, st, sc, sidx, sord, null);
            //List<Lyrics> genres = (List<Lyrics>)Lyrics.Search(page??1, 30, sidx, sord, st, so, sc, null);
            return View(lyricss);
        }

        //[OutputCache(Duration = 1, Location = OutputCacheLocation.None, NoStore = true)]
        //[RequireSiteFilter]
        //[NavigationHistoryFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Edit(Guid code)
        {
            Lyrics obj = null;
            obj = Lyrics.Fetch(code, null, CurrentUserId);
            string title = "Edit Lyrics";

            if (obj == null)
            {
                //return NotFound();
                obj = Lyrics.New();
                obj.Code = code;
                obj.IsNew = true;
                title = "Add New Lyrics";
                obj.Genre = Genre.New();
                obj.Artist = Artist.New();
                obj.Genre.Code = Guid.NewGuid();
                obj.Artist.Id = Guid.NewGuid();
            }
            else
            {
                obj.IsNew = false;
            }
            List<ItemDTO> genres = new List<ItemDTO>();
            List<Genre> gens = Genre.FetchAll(CurrentUserId, null);
            foreach (Genre genre in gens)
            {
                genres.Add(new ItemDTO { Text = genre.GenreText, Value = genre.Code.ToString() });
            }
            ViewData["Genres"] = new SelectList(genres, "Value", "Text", obj.Genre.GenreText);

            List<ItemDTO> artists = new List<ItemDTO>();
            List<Artist> arts = Artist.FetchAll(CurrentUserId, null);
            foreach (Artist a in arts)
            {
                artists.Add(new ItemDTO { Text = a.Name, Value = a.Id.ToString() });
            }
            ViewData["artists"] = new SelectList(artists, "Value", "Text", obj.Artist.Name);

            ViewBag.PageTitle = title;
            return View(obj);
        }

        [ActionName("Edit")]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "SysAdmin")]
        //[RequireSiteFilter]
        public ActionResult OnEdit(Guid code, string txtTitle, string txtText, Guid Genres, Guid artists, string txtCorrectAnswer, string txtWrongAnswer1, string txtWrongAnswer2, string txtWrongAnswer3)
        {

            Lyrics obj = null;
            obj = Lyrics.Fetch(code, null, CurrentUserId);

            //obj.IsNew = false;
            if (obj == null)
            {
                obj = Lyrics.New();
                obj.IsNew = true;
                obj.Code = code;
            }
            else
                obj.IsNew = false;

            try
            {
                obj.Title = txtTitle.Trim();
                obj.LyricsText = txtText.Trim();
                obj.CorrectAnswer = txtCorrectAnswer;
                obj.WrongAnswer1 = txtWrongAnswer1;
                obj.WrongAnswer2 = txtWrongAnswer2;
                obj.WrongAnswer3 = txtWrongAnswer3;

                Genre genre = Genre.New();
                genre.Code = Genres;
                obj.Genre = genre;

                Artist a = Artist.New();
                a.Id = artists;
                obj.Artist = a;

                obj.Save(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            //return View();
            return Redirect(Url.Action("List"));
        }

        //[RequireSiteFilter]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "SysAdmin")]
        public ActionResult Add()
        {
            return RedirectToAction("Edit", new { code = Guid.NewGuid() });
            //return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Delete(Guid code)
        {
            Lyrics obj = null;
            //TODO : FIX HACK
            try
            {
                obj = Lyrics.Fetch(code, null, CurrentUserId);

                if (obj != null)
                    obj.Delete(CurrentUserId, null);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    deleted = false
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                deleted = true
            }, JsonRequestBehavior.AllowGet);
        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////API METHODS///////////////////////////////////////////////////////////////
        public JsonResult GetByGenre(Guid code)
        {
            try
            {
                List<Lyrics> ques = Lyrics.FetchByGenre(code, null, CurrentUserId);
                List<ApiShortLyrics> lyricss = new List<ApiShortLyrics>();
                foreach (Lyrics q in ques)
                {
                    lyricss.Add(new ApiShortLyrics
                    {
                        Code = q.Code,
                        Title = q.Title,
                        Text = q.LyricsText,
                        Artist = q.Artist.Name
                    });
                }
                return Json(new { Success = true, Data = lyricss }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Get(Guid code)
        {
            try
            {
                Lyrics ques = Lyrics.Fetch(code, null, CurrentUserId);

                ApiLyrics q = new ApiLyrics
                {
                    Code = ques.Code,
                    Title = ques.Title,
                    Text = ques.LyricsText,
                    CorrectAnswer = ques.CorrectAnswer,
                    WrongAnswer1 = ques.WrongAnswer1,
                    WrongAnswer2 = ques.WrongAnswer2,
                    WrongAnswer3 = ques.WrongAnswer3
                };

                return Json(new { Success = true, Data = q }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

app/SplitMe/Areas/Data1/Views/Lyrics/Edit.cshtml
@model SplitMe.Domain.Lyrics
@using SplitMe.Domain
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("Edit", new {code = Request["code"] }, new AjaxOptions { LoadingElementId = "updating", UpdateTargetId = "validation" }, new { id = "targetform", @class = "form-horizontal" }))
{
        <h2>@ViewBag.PageTitle</h2>

        <div class="row">
            <div class="span3">&nbsp;</div>
                <div class="span8">

                <div class="control-group">

                    <label class="control-label" for="txtGenre">
                        Genre:</label>
                    <div class="controls">
                        @Html.DropDownList("Genres", null, new { @class = "textbox" })
                    </div>
                </div>

                <div class="control-group">

                    <label class="control-label" for="txtArtist">
                        Artist:</label>
                    <div class="controls">
                        @Html.DropDownList("artists", null, new { @class = "textbox" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="txtTitle">
                        Lyrics Title</label>
                    <div class="controls">
                        @Html.TextBox("txtTitle", Model.Title, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>

                <div class="control-group">
                    <label class="control-label" for="txtText">
                        Lyrics Text</label>
                    <div class="controls">
                        @Html.TextBox("txtText", Model.LyricsText, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>
                <div class="control-group">
                    <label class="control-label" for="txtCorrectAnswer">
                        Correct Answer</label>
                    <div class="controls">
                        @Html.TextBox("txtCorrectAnswer", Model.CorrectAnswer, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>
                <div class="control-group">
                    <label class="control-label" for="txtWrongAnswer1">
                        Wrong Answer</label>
                    <div class="controls">
                        @Html.TextBox("txtWrongAnswer1", Model.WrongAnswer1, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>
                <div class="control-group">
                    <label class="control-label" for="txtWrongAnswer2">
                        Wrong Answer</label>
                    <div class="controls">
                        @Html.TextBox("txtWrongAnswer2", Model.WrongAnswer2, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>
                <div class="control-group">
                    <label class="control-label" for="txtWrongAnswer3">
                        Wrong Answer</label>
                    <div class="controls">
                        @Html.TextBox("txtWrongAnswer3", Model.WrongAnswer3, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>

                </div>
                @*<div class="control-group">
                    <label class="control-label" for="txtQuestion">
                        Question Text</label>
                    <div class="controls">
                        @Html.TextBox("txtQuestion", Model.QuestionText, new Dictionary<string, object> { { "class", "textbox" }, { "maxlength", "50" } })
                    </div>
                </div>*@

                @*<div class="control-group">
                    <label class="control-label" for="txtQuestion">
                        Answers: </label>
                    <div class="controls">
                        @foreach(Answer ans in Model.Answers)
                        {
                            Html.RenderPartial("Answers", ans);
                        }
                    </div>
                </div>*@
            </div>
        </div>
        string delScript = "deleteLyrics('" + Model.Code + "');";    
        <div class="row">
            <div class="span12 well centered">
			    <a class="btn btn-danger" href="#" onclick="@delScript"><i class="icon-trash icon-white"></i> Delete</a>
			    <a class="btn btn-primary" href="#"  onclick="$('#targetform').submit();">Save</a>
            </div>
        </div>
}

app/SplitMe/Areas/Data1/Views/Lyrics/List.cshtml
@model SplitMe.Common.Data.IPagedList<SplitMe.Domain.Lyrics>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using SplitMe.MVC.Extensions;

<div class="row">
    <div class="span2 well centered">
		<a class="btn btn-primary" href="@Url.Action("Add", "Lyrics")">Add New</a>
    </div>
</div>
<div class="row">
    <div id="dvQuestions" class="span12">
        @Html.Partial("LyricsList", Model);
    </div>
</div>

app/SplitMe/Areas/Data1/Views/Lyrics/LyricsList.cshtml
@model SplitMe.Common.Data.IPagedList<SplitMe.Domain.Lyrics>
@using SplitMe.MVC.Extensions
@{
 object rvs = new
    {
        sidx = Request["sidx"],
        sord = Request["sord"],
        so = ViewData["so-val"],
        st = ViewData["st-val"],
        sc = Html.Encode(ViewData["sc-val"]),
        //rid = Request["rid"],
        snl = Request["snl"]
    };

 AjaxOptions ajo = new AjaxOptions { UpdateTargetId = "dvQuestions", LoadingElementId = "updating", InsertionMode = InsertionMode.Replace };
    
    <div id="updatingWrapper">
        <div id="updating">
        </div>
    </div>

    <div id="divQuestionSearch">
        @using (Ajax.BeginForm("List", rvs, ajo, new { @class = "well form-horizontal form-inline" }))
        {
            <fieldset>
                @Html.DropDownList("so")
                @Html.DropDownList("st")
                @Html.TextBox("sc", ViewData["sc-val"])
                <input class="btn" type="submit" value="Search" />
            </fieldset>
        }
    </div>

    if (Model == null || Model.Count <= 0)
    {
        Html.RenderPartial("NoRecords", "");

    }
    else
    { 
            <table id="ListViewQuestion" class="table table-bordered table-condensed"  cellspacing="0">
                <thead>
                    <tr>

                        <th>
                            @Html.Raw(Ajax.SortableColumn("Ttile", "2", rvs, ajo))
                        </th>
				
                        <th>
                            @Html.Raw(Ajax.SortableColumn("Text", "3", rvs, ajo))
                        </th>
				
                        <th>
                            @Html.Raw(Ajax.SortableColumn("Genre", "1", rvs, ajo))
                        </th>
				
                        <th>
                            @Html.Raw(Ajax.SortableColumn("Artist", "4", rvs, ajo))
                        </th>
                    </tr>
                </thead>
        
                <tbody>
                @{string style = string.Empty;
                  int ix = 0;
                  foreach (SplitMe.Domain.Lyrics lyrics in Model)
                  {
                      style = ix % 2 == 0 ? "AltListItem" : "ListItem";

                      ix++;

                        <tr class="@style">
                            <td>@Html.ActionLink(lyrics.Title, "Edit", "Lyrics", new { code = lyrics.Code }, null)</td>
                            <td>@lyrics.LyricsText</td>
                            <td>@lyrics.Genre.GenreText</td>
                            <td>@lyrics.Artist.Name</td>
                        </tr>
                  }
                }
                </tbody>

            </table>
   
            <div class="pagination pagination-centered">
                 @Html.Raw(Ajax.Pager(new AjaxOptions
                    {
                        UpdateTargetId = "dvQuestions",
                        LoadingElementId = "updating"
                    },
		            ViewData.Model.PageSize, ViewData.Model.PageNumber, ViewData.Model.TotalItemCount, 
                    new { controller = "Question", action = "List", sidx=Request["sidx"], sord=Request["sord"],
                          so = ViewData["so-val"],
                          st = ViewData["st-val"],
                          sc = Html.Encode(ViewData["sc-val"]), snl = Request["snl"]
                    }))
             </div>
        }
}